<html lang="en">

<head>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.min.css">
</head>

<body>
    
          <form method="post">

            <label>Name:</label><br>
            <input type="text" id="name" name="name" placeholder="Enter the name of the Mitre Tactic"><br>

            <label>ID:</label><br>
            <input type="text" id="id" name="id" placeholder="Enter the ID for the Mitre Tactic"><br>
  
            <label>Description:</label><br>
            <input type="text" id="description" name="description" placeholder="Enter the description of the Mitre Tactic"><br>

            <input type="submit" value="Add Tactic">
          </form>
    

    <a href="/">Back</a>

</body>
</html>